apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkube-it-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wkube-it-gateway
  template:
    metadata:
      labels:
        app: wkube-it-gateway
    spec:

      volumes:
        - name: tls-certs
          secret:
            secretName: at.ac.iiasa.wkube
      
      containers:
        - name: wkube-it-gateway
          image: registry.iiasa.ac.at/accelerator/wkube-it-gateway:4ba1bff
          imagePullPolicy: Always
          env:
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: wkube-it-gateway-ssh-keys
                  key: id_ed25519.pub
            - name: PASSWORD_ACCESS
              value: "false"
          
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/ssl/certs"
              readOnly: true
          
          ports:
          - containerPort: 6473
          - containerPort: 2222
          resources:  
            limits:
              memory: "2048Mi"
              cpu: "2000m"
            requests:
              memory: "2048Mi"
              cpu: "2000m"

      imagePullSecrets:
        - name: iiasaregcred
---
apiVersion: v1
kind: Service
metadata:
  name: wkube-it-gateway-service
spec:
  type: NodePort
  selector:
    app: wkube-it-gateway
  ports:
    - protocol: TCP
      port: 8913
      targetPort: 6473
      nodePort: 30153
---
apiVersion: v1
kind: Service
metadata:
  name: wkube-it-gateway-sshd-service
spec:
  type: NodePort
  selector:
    app: wkube-it-gateway
  ports:
    - protocol: TCP
      port: 8914
      targetPort: 2222
      nodePort: 30188