apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rwx
provisioner: rwx
parameters:
  archiveOnDelete: "false"           # don't keep PVC folders after delete
mountOptions:
  - vers=4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
